services:
  - type: web
    name: haramaya-health-center
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn health_center.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DATABASE_URL
        fromDatabase:
          name: haramaya-health-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4

databases:
  - name: haramaya-health-db
    databaseName: haramaya_health
    user: haramaya_user
